BiasedSocialMedia.Web/Models/Notifications.cs
using BiasedSocialMedia.Web.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BiasedSocialMedia.Web.Models
{
    public class Notifications
    {
        public int Id { get; set; }
        public NotificationType NType { get; set; }
        public int ForUser { get; set; }
        public int ByUserID { get; set; }
        public virtual Users ByUser { get; set; }
        public int NPostPostId { get; set; }
        public virtual Posts NPost { get; set; }
    }
}

BiasedSocialMedia.Web/Controllers/HomeController.cs
using BiasedSocialMedia.Web.Models;
using BiasedSocialMedia.Web.Utilities;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;

namespace BiasedSocialMedia.Web.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private IUserData userData;
        private IImageHelper imageHelper;
        private IPostHelper postHelper;
        public HomeController(IImageHelper imageHelper, IUserData userData, IPostHelper postHelper)
        {
            this.imageHelper = imageHelper;
            this.userData = userData;
            this.postHelper = postHelper;
        }

        public ActionResult Index()
        {
            DashboardViewModel model = new DashboardViewModel();
            var userid = User.Identity.Name;
            model.CurrentUser = userData.getUser(Convert.ToInt32(User.Identity.Name));
            model.UserNotifications = postHelper.UserNotification(Convert.ToInt32(User.Identity.Name));
            return View(model);
        }

        #region Child actions
        public ActionResult _DashboardUserInfo()
        {
            return View();
        }
        public ActionResult _NotificationArea()
        {
            return View();
        }
        public ActionResult _SingleNotification()
        {
            return View();
        }
        public ActionResult _PostArea(int? id)
        {
            if (id != null && id != 0)
            {
                return PartialView(postHelper.GetAllPostByPageAndUserId(0, Convert.ToInt32(id)));
            }
            return PartialView(postHelper.GetAllPostByPage(0));
        }
        public ActionResult _SinglePost()
        {
            return View();
        }
        public ActionResult _WritePost()
        {
            return View();
        }
        #endregion

        #region PostRegion
        [HttpPost]
        public async Task<ActionResult> SubmitPost(string PostContent, IEnumerable<HttpPostedFileBase> files)
        {
            Posts post = postHelper.CreatePost(Convert.ToInt32(User.Identity.Name), PostContent);
            if (files != null)
            {
                List<PostMediaMap> postMediaMap = new List<PostMediaMap>();
                foreach (HttpPostedFileBase file in files)
                {
                    PostMediaMap pm = new PostMediaMap();
                    pm.PostsPostID = post.PostID;
                    pm.PostMediaId = await imageHelper.InsertImageToDbAsync(file);
                    postMediaMap.Add(pm);
                }
                postHelper.SavePostMediaMaps(postMediaMap);
            }
            return PartialView("_PostArea", postHelper.GetAllPosts());
        }
        #endregion

        public ActionResult GetPostArea(int page)
        {
            return PartialView("_PostArea", postHelper.GetAllPostByPage(page));
        }
        public ActionResult LikePost(int? postId, int? status)
        {
            Dictionary<string, int> counts = postHelper.LikePost(Convert.ToInt32(postId), Convert.ToInt32(status), Convert.ToInt32(User.Identity.Name));
            bool isSuccess = true;
            if (counts == null)
                isSuccess = false;
            return Json(new { counts, isSuccess = isSuccess }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Notifications()
        {
            return View(postHelper.UserNotification(Convert.ToInt32(User.Identity.Name)));
        }
        public ActionResult GetNotifications(int? page)
        {
            return PartialView("NotificationAreaFullPage", postHelper.GetNotificationByPage(Convert.ToInt32(page), Convert.ToInt32(User.Identity.Name)));
        }
        //public ActionResult Test()
        //{
        //    Debug.WriteLine("Action is executing");
        //    return View();
        //}
        //[HttpPost]
        //public async Task<ActionResult> Test(string PostContent,IEnumerable<HttpPostedFileBase> files)
        //{

        //    Posts post = postHelper.CreatePost(Convert.ToInt32(User.Identity.Name), PostContent);
        //    List<PostMediaMap> postMediaMap = new List<PostMediaMap>();
        //    foreach(HttpPostedFileBase file in files)
        //    {
        //        PostMediaMap pm = new PostMediaMap();
        //        pm.PostsPostID = post.PostID;
        //        pm.PostMediaId = await imageHelper.InsertImageToDbAsync(file);
        //    }
        //    postHelper.SavePostMediaMaps(postMediaMap);
        //    return Json(new {data=postImgs });
        //}
        [AllowAnonymous]
        public ActionResult BackendPost(int userid,string postcontent)
        {
            postHelper.CreatePost(userid, postcontent);
            return Json(new { status = "OK" }, JsonRequestBehavior.AllowGet);
        }
    }
}

BiasedSocialMedia.Web/Controllers/ImageController.cs
using BiasedSocialMedia.Web.Utilities;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace BiasedSocialMedia.Web.Controllers
{
    public class ImageController : Controller
    {
        private IImageHelper imageHelper;
        public ImageController(IImageHelper imageHelper)
        {
            this.imageHelper = imageHelper;
        }
        // GET: Image
        public async Task<ActionResult> Images(int? id)
        {
            if (id == null)
            {
                id = 1;
            }
            byte[] img = await imageHelper.GetImageFromDB(Convert.ToInt32(id));
            return File(img, "image/jpeg");
        }
        public async Task<ActionResult> ImageByUserId(int? id)
        {
            if (id == null)
            {
                id = 1;
            }
            byte[] img = await imageHelper.GetImageFromDBByUserId(Convert.ToInt32(id));
            if(img==null)
            {
                return File(imageHelper.GetDefaultImage(), "image/jpeg"); ;
            }
            return File(img, "image/jpeg");
        }
    }
}

BiasedSocialMedia.Web/Controllers/ProfileController.cs
using BiasedSocialMedia.Web.Models;
using BiasedSocialMedia.Web.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace BiasedSocialMedia.Web.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        // GET: Profile
        private IUserData userData;
        private IPostHelper postHelper;
        private IImageHelper imageHelper;
        public ProfileController(IImageHelper imageHelper, IUserData userData, IPostHelper postHelper)
        {
            this.userData = userData;
            this.postHelper = postHelper;
            this.imageHelper = imageHelper;
        }
        public ActionResult Index(int? id)
        {
            //ProfileViewModel model = new ProfileViewModel();
            //var userid = Convert.ToInt32(User.Identity.Name);
            //model.CurrentUser = userData.getUser(userid);
            return View();
        }
        public ActionResult LoadProfileInfo(int? id)
        {
            if (id != null && id != 0)
            {
                int currentID = Convert.ToInt32(id);
                var userInfo = userData.getUser(currentID);
                if (currentID == Convert.ToInt32(User.Identity.Name))
                {
                    return PartialView("_EditProfile", userInfo);
                }
                else
                {
                    return PartialView("_FriendProfile", userInfo);
                }
            }
            return PartialView();
        }
        [HttpPost]
        public ActionResult UpdateProfile(Users user)
        {
            userData.updateData(user.ID.ToString(), user.Name, user.PhoneNumber, user.Gender, user.UserName);
            return Json(new {isSuccess=true});
        }
        public ActionResult _ChangeProfilePhoto()
        {
            ViewBag.UserID = User.Identity.Name;
            return PartialView();
        }
        [HttpPost]
        public async Task<ActionResult> ChangeProfilePhoto(HttpPostedFileBase files)
        {
            int mediaid = await imageHelper.InsertImageToDbAsync(files);
            userData.UpdateUserImage(User.Identity.Name, mediaid);
            return Json(new {isSuccess=true});
        }
    }
}

BiasedSocialMedia.Web/Views/Home/Index.cshtml
@model BiasedSocialMedia.Web.Models.DashboardViewModel
@{
    ViewBag.Title = "Home Page";
}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            @{ Html.RenderPartial("_WritePost");}
            <div id="all-posts-container">
                @*@{ Html.RenderPartial("_PostArea", Model.Posts);}*@
            </div>
            <div id="posts-loader">
                <div class="d-flex justify-content-center align-items-center">
                    <img src="~/Content/Images/test-loader.gif" />
                    <p>Loading contents</p>
                </div>
            </div>
        </div>
        <div class="col-md-4 dashboard-right-panel">
            <!--user login area-->
            @{ Html.RenderPartial("_DashboardUserInfo", Model.CurrentUser);}
            <!--user login area-->
            @{ Html.RenderPartial("_NotificationArea",Model.UserNotifications);}
        </div>
    </div>
</div>
@Scripts.Render("~/bundles/Dashboard")

BiasedSocialMedia.Web/Views/Home/NotificationAreaFullPage.cshtml
@model IEnumerable<BiasedSocialMedia.Web.Models.Notifications>
@{ foreach (BiasedSocialMedia.Web.Models.Notifications notification in Model)
    {
        Html.RenderPartial("_SingleNotification", notification);
    }
}

BiasedSocialMedia.Web/Views/Home/Notifications.cshtml
@model IEnumerable<BiasedSocialMedia.Web.Models.Notifications>
@{
    ViewBag.Title = "Notifications";
}
<style>
</style>
<div class="container">
    <a href="~/Home/" type="button" class="btn btn-outline-info mb-2">
        <i class="fa fa-arrow-left" aria-hidden="true"></i>
        Back
    </a>
    <div class="my-card">
        <h2>Notifications</h2>
        <hr />
        <div id="all-notification-cards">
            <div id="notification-loader">
                <div class="d-flex justify-content-center align-items-center">
                    <img src="~/Content/Images/test-loader.gif" />
                    <p>Loading notifications</p>
                </div>
            </div>
        </div>
        @*@{
            if (Model.Count() == 0)
            {
                <h6>No notification yet.</h6>
            }
            else
            {
                foreach (BiasedSocialMedia.Web.Models.Notifications notifications in Model)
                {
                    Html.RenderPartial("_SingleNotification", notifications);
                }
            }
        }*@
    </div>

</div>
@Scripts.Render("~/bundles/Notifications")

BiasedSocialMedia.Web/Views/Home/Test.cshtml
@{
    ViewBag.Title = "Test";
}

<h2>Test</h2>
<form action="Test" method="post">
    <input type="number" name="TestProperty"/>
    <input type="file" id="test-image" multiple/>
    <button type="submit" class="my-test">Click</button>
</form>
<script type="text/javascript">
    $('.my-test').click(function (e) {
        e.preventDefault();
        var fileData = new FormData();
        fileData.append("PostContent", "posticonedjfoidf0dfkjojfodkfldfldkflkdlfldfkdnt");

        var fileUpload = $("#test-image").get(0);
        var files = fileUpload.files;
        for (var i = 0; i < files.length; i++) {
            fileData.append("files", files[i]);
        }

        $.ajax({
            url: "/Home/Test",
            type: "POST",
            processData: false,
            contentType: false,
            data: fileData,
            success: function (data) {
                console.log(data)
            }
        })
    })
</script>

BiasedSocialMedia.Web/Views/Home/_DashboardUserInfo.cshtml
@model BiasedSocialMedia.Web.Models.Users
<div class="user-login-status my-card d-flex">
    <img class="profile-photo" src="@Url.Action("Images","Image",new {id=Model.ProfilePhotoID})" height="80" width="80" />
    <div>
        @*@Html.ActionLink("Index", "Index", "Profile", new { area = "" }, new { @class = "text-dark" })*@
        <h5>@Model.Name</h5>
        <a href="@Url.Action("Index","Profile",new {id=Model.ID})">
            <p>@@@Model.UserName</p>
        </a>
        <p><i class="fa fa-circle" style="color:green;font-size:10px;"></i> Active</p>
    </div>
</div>

BiasedSocialMedia.Web/Views/Home/_NotificationArea.cshtml
@model IEnumerable<BiasedSocialMedia.Web.Models.Notifications>
<div class="notification-area my-card">
    <h4>
        New Notifications <span class="badge text-bg-dark">@Model.Count()</span>
    </h4>
    <hr />
    @{
        if (Model.Count() == 0)
        {
            <h6>No notification yet.</h6>
        }
        else
        {
            foreach (BiasedSocialMedia.Web.Models.Notifications notifications in Model)
            {
                Html.RenderPartial("_SingleNotification", notifications);
            }
        }
    }
</div>

BiasedSocialMedia.Web/Views/Home/_PostArea.cshtml
@model IEnumerable<BiasedSocialMedia.Web.Models.Posts>
@{ foreach (BiasedSocialMedia.Web.Models.Posts post in Model)
    {
        Html.RenderPartial("_SinglePost", post);
    }
}

BiasedSocialMedia.Web/Views/Home/_SingleNotification.cshtml
@model BiasedSocialMedia.Web.Models.Notifications
<div class="single-notification my-card d-flex my-card-hover">
    <div>
        <a href="@Url.Action("Index","Profile",new {id=Model.ByUserID})"><img src="@Url.Action("Images","Image",new {id=Model.ByUser.ProfilePhotoID})" height="50" width="50" class="profile-photo" /></a>
</div>
    <div class="notification-content max-lines">
        <p>@Model.ByUser.Name liked your @Model.NPost.PostContent</p>
        <p>
            <span class="notification-time">Few Minutes Ago</span>
        </p>
    </div>
</div>

BiasedSocialMedia.Web/Views/Home/_SinglePost.cshtml
@model BiasedSocialMedia.Web.Models.Posts
<div class="post-body my-card my-card-hover">
    <div class="single-post d-flex">
        <div>
            <a href="@Url.Action("Index","Profile",new {id=Model.User.ID})"><img src="@Url.Action("Images","Image",new {id=Model.User.ProfilePhotoID})" height="90" width="90" class="profile-photo" /></a>
        </div>
        <div style="width:100%">
            <div><h5 class="mb-0">@Model.User.Name</h5><p class="m-0 text-muted">@@@Model.User.UserName</p></div>
            <p class="max-lines">@Model.PostContent</p>
            @*<div>
                <img src="~/Content/Images/total-posts.png" style="object-fit:cover" height="100" width="100"/>
                <img src="~/Content/Images/total-posts.png" style="object-fit:cover" height="100" width="100"/>
            </div>*@
            <div style="display: flex; width:100%">
                <div class="d-flex justify-content-center align-items-center post-like-btn" data-id="@Model.PostID" style="cursor:pointer">
                    <p style="margin-right: 5px">@Model.LikeCount</p><i class="fa fa-thumbs-o-up"></i>
                </div>
                <div class="d-flex justify-content-lg-center align-items-center" style="cursor:pointer">
                    <p style="margin-right: 5px">0</p><span class="fa fa-thumbs-o-down"></span>
                </div>
                <div class="d-flex justify-content-lg-center align-items-center" style="cursor:pointer">
                    <p style="margin-right: 5px">100</p><span class="fa  fa-comment-o"></span>
                </div>
                @*<p style="margin-right: 8px;"><span class="fa fa-ellipsis-v"></span></p>*@
                <p class="single-post-date mt-2" style="margin-left:auto">@Model.GetPostTimeInString()</p>
            </div>
        </div>
    </div>
</div>

BiasedSocialMedia.Web/Views/Home/_WritePost.cshtml
<div>
    <div class="post-area my-card">
        <textarea class="form-control" id="post-text-area" rows="3" cols="20" placeholder="Post Something Here"></textarea>
        <div class="group" style="margin-top: 5px;">
            <label class="upload-image-label" style="float: left;" for="input-post-upload">Upload Image</label>
            <input type='file' accept='image/*' onchange="" id="input-post-upload" hidden multiple>
            <button type="submit" id="btn-submit-post"
                    style="float: right;width: 120px; height: 30px;border-radius: 10px;">
                <span>Post</span>
            </button>
        </div>
    </div>
</div>